apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: udagram-frontend
          image: cesairenj/udagram-frontend
          ports:
            - containerPort: 8100
          livenessProbe:
            httpGet:
              path: /health
              port: 8100
            initialDelaySeconds: 3
            periodSeconds: 3